name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/30 * * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 升级到了稳定的 v4 版本
      - name: Update gist
        # 替换为社区持续维护并支持新版环境的 waka-box-fast
        uses: g1eny0ung/waka-box@v6 
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 3a1b94579d76261eb4749796f4879fb4
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
